### ISSUE TITLE
Suddenly stopped working

### ISSUE THREAD

**Issue by RobertGoulding** [lijyze/scroll-offset#4]
When I went to work in Obsidian today, Scroll Offset was no longer working. I disabled all other community plugins just in case there was a conflict, but it just wouldn't work. Perhaps because Obsidian just update of 0.15.6?

**Comment by RobertGoulding** [comment]
Sorry, I see that that is essentially the content of the other open bug at the moment.

**Comment by lijyze** [comment]
#3
